using KieshStockExchange.Helpers;
using KieshStockExchange.Models;
using KieshStockExchange.Services.MarketEngineServices.Interfaces;

namespace KieshStockExchange.Services.MarketEngineServices;

/// <summary> Indicates the outcome of an order placement attempt. </summary>
public enum OrderStatus
{
    Success,
    NotAuthenticated,
    InvalidParameters,
    PriceTooLow,
    PriceTooHigh,
    InsufficientStocks,
    InsufficientFunds,
    NoMarketPrice,
    NoLiquidity,
    AlreadyClosed,
    NotAuthorized,
    OperationFailed,
    PartialFill,
    Filled,
    PlacedOnBook
}

/// <summary>
/// Detailed result for a buy or sell order:
/// <see cref="Status"/> tells you if it succeeded or why it failed, and
/// <see cref="FillTransactions"/> holds any Transaction records created by fills.
/// </summary>
public class OrderResult
{
    #region Status and Fills
    /// <summary> Reason the order did — or did not — go through. </summary>
    public OrderStatus Status { get; set; }

    /// <summary>
    /// All individual trade transactions generated by matching. Empty if the order went
    /// straight on-book (e.g. an unfilled limit). Assign through this setter so the
    /// totals below stay in sync.
    /// </summary>
    public IReadOnlyList<Transaction> FillTransactions
    {
        get => _fillTransactions;
        set => SetFillTransactions(value);
    }
    private IReadOnlyList<Transaction> _fillTransactions = Array.Empty<Transaction>();

    /// <summary> Total shares actually filled across <see cref="FillTransactions"/>. </summary>
    public int TotalFilledQuantity { get; private set; }

    /// <summary> Weighted-average price across all fills; zero if nothing filled. </summary>
    public decimal AverageFillPrice { get; private set; }
    #endregion

    #region Placed Order
    /// <summary>
    /// The original order handed to the market/user service. Its quantity is adjusted
    /// down by any fills so callers can see how much is still resting, if any.
    /// </summary>
    public Order? PlacedOrder { get; set; } = null;

    /// <summary>
    /// For orders that go on-book (limit orders, partial fills), this is the remaining
    /// quantity still outstanding.
    /// </summary>
    public int RemainingQuantity => PlacedOrder?.RemainingQuantity ?? 0;

    /// <summary>
    /// If a new resting order was created (e.g. an unfilled limit), this is its
    /// database-assigned ID so the UI can reference or cancel it later.
    /// </summary>
    public int? NewOrderId => PlacedOrder?.OrderId > 0 ? PlacedOrder.OrderId : null;
    #endregion

    #region Messages and State
    /// <summary> Optional success message for UI display. </summary>
    public string SuccessMessage { get; set; } = string.Empty;

    /// <summary> Optional error message for UI display. </summary>
    public string ErrorMessage { get; set; } = string.Empty;

    /// <summary>
    /// True when the order was placed successfully — fully filled, partially filled,
    /// or resting on the order book.
    /// </summary>
    public bool PlacedSuccessfully =>
        Status == OrderStatus.Success ||
        Status == OrderStatus.PartialFill ||
        Status == OrderStatus.Filled ||
        Status == OrderStatus.PlacedOnBook;
    #endregion

    #region Helpers
    // Recompute total filled quantity and weighted-average fill price whenever the
    // transaction list is replaced.
    private void SetFillTransactions(IReadOnlyList<Transaction> value)
    {
        _fillTransactions = value ?? Array.Empty<Transaction>();

        int totalQty = 0;
        decimal notional = 0m;
        for (int i = 0; i < _fillTransactions.Count; i++)
        {
            var tx = _fillTransactions[i];
            totalQty += tx.Quantity;
            notional += CurrencyHelper.Notional(tx.Price, tx.Quantity, tx.CurrencyType);
        }
        TotalFilledQuantity = totalQty;
        AverageFillPrice = totalQty > 0 ? notional / totalQty : 0m;
    }
    #endregion
}
