// <auto-generated />
using System;
using KieshStockExchange.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KieshStockExchange.Server.Data.Migrations
{
    [DbContext(typeof(KseDbContext))]
    [Migration("20260604013020_StopOrders")]
    partial class StopOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KieshStockExchange.Services.DataServices.Persistence.AIUserRow", b =>
                {
                    b.Property<int>("AiUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AiUserId"));

                    b.Property<decimal>("AggressivenessPrc")
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("BuyBiasPrc")
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("CashInjectionAmountPrc")
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("CashInjectionFrequencyPrc")
                        .HasColumnType("numeric(20,10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DecisionIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExtremeReactionRandomnessPrc")
                        .HasColumnType("numeric(20,10)");

                    b.Property<string>("HomeCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxCashReservePrc")
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("MaxLimitOffsetPrc")
                        .HasColumnType("numeric(20,10)");

                    b.Property<int>("MaxOpenOrders")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxTradeAmountPrc")
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("MinCashReservePrc")
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("MinLimitOffsetPrc")
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("MinTradeAmountPrc")
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("PerPositionMaxPrc")
                        .HasColumnType("numeric(20,10)");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<decimal>("SlippageTolerancePrc")
                        .HasColumnType("numeric(20,10)");

                    b.Property<int>("StrategyCode")
                        .HasColumnType("integer")
                        .HasColumnName("Strategy");

                    b.Property<decimal>("TradeProb")
                        .HasColumnType("numeric(20,10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UseMarketProb")
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("UseSlippageMarketProb")
                        .HasColumnType("numeric(20,10)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("WatchlistCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AiUserId");

                    b.HasIndex("StrategyCode");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserAi");

                    b.ToTable("AIUsers", (string)null);
                });

            modelBuilder.Entity("KieshStockExchange.Services.DataServices.Persistence.CandleRow", b =>
                {
                    b.Property<int>("CandleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CandleId"));

                    b.Property<int>("BucketSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric(20,10)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric(20,10)");

                    b.Property<int?>("MaxTransactionId")
                        .HasColumnType("integer");

                    b.Property<int?>("MinTransactionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric(20,10)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("CandleId");

                    b.HasIndex("StockId", "Currency", "BucketSeconds", "OpenTime")
                        .IsUnique()
                        .HasDatabaseName("IX_Candle_Key");

                    b.ToTable("Candles", (string)null);
                });

            modelBuilder.Entity("KieshStockExchange.Services.DataServices.Persistence.FundRow", b =>
                {
                    b.Property<int>("FundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FundId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ReservedBalance")
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("TotalBalance")
                        .HasColumnType("numeric(20,10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FundId");

                    b.HasIndex("UserId", "Currency")
                        .IsUnique()
                        .HasDatabaseName("IX_Funds_User_Currency");

                    b.ToTable("Funds", null, t =>
                        {
                            t.HasCheckConstraint("CK_Funds_Balance_Invariants", "\"TotalBalance\" >= 0 AND \"ReservedBalance\" >= 0 AND \"ReservedBalance\" <= \"TotalBalance\"");
                        });
                });

            modelBuilder.Entity("KieshStockExchange.Services.DataServices.Persistence.FundTransactionRow", b =>
                {
                    b.Property<int>("FundTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FundTransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(20,10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FundTransactionId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_FundTx_User_Time");

                    b.ToTable("FundTransactions", (string)null);
                });

            modelBuilder.Entity("KieshStockExchange.Services.DataServices.Persistence.MessageRow", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("MessageId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Messages_Created");

                    b.HasIndex("UserId", "ReadAt")
                        .HasDatabaseName("IX_Messages_User_Read");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("KieshStockExchange.Services.DataServices.Persistence.OrderRow", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<int>("AmountFilled")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BuyBudget")
                        .HasColumnType("numeric(20,10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(20,10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SlippagePercent")
                        .HasColumnType("numeric(20,10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StopPrice")
                        .HasColumnType("numeric(20,10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("StockId", "Status")
                        .HasDatabaseName("IX_Orders_Stock_Status");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_Orders_User_Status");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("KieshStockExchange.Services.DataServices.Persistence.PositionRow", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PositionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("ShortCollateral")
                        .HasColumnType("numeric(20,10)");

                    b.Property<string>("ShortCollateralCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PositionId");

                    b.HasIndex("UserId", "StockId")
                        .IsUnique()
                        .HasDatabaseName("IX_Positions_User_Stock");

                    b.ToTable("Positions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Positions_Quantity_Invariants", "\"ReservedQuantity\" >= 0 AND \"ReservedQuantity\" <= GREATEST(\"Quantity\", 0) AND \"ShortCollateral\" >= 0 AND (\"Quantity\" >= 0 OR \"ReservedQuantity\" = 0) AND (\"Quantity\" < 0 OR \"ShortCollateral\" = 0)");
                        });
                });

            modelBuilder.Entity("KieshStockExchange.Services.DataServices.Persistence.StockListingRow", b =>
                {
                    b.Property<int>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ListingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<decimal>("SeedPrice")
                        .HasColumnType("numeric(20,10)");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.HasKey("ListingId");

                    b.HasIndex("StockId", "Currency")
                        .IsUnique()
                        .HasDatabaseName("IX_StockListing");

                    b.ToTable("StockListings", (string)null);
                });

            modelBuilder.Entity("KieshStockExchange.Services.DataServices.Persistence.StockPriceRow", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriceId"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(20,10)");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PriceId");

                    b.HasIndex("StockId", "Currency", "Timestamp")
                        .HasDatabaseName("IX_StockPrices_Stock_Curr_Time");

                    b.ToTable("StockPrices", (string)null);
                });

            modelBuilder.Entity("KieshStockExchange.Services.DataServices.Persistence.StockRow", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StockId");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Stocks", (string)null);
                });

            modelBuilder.Entity("KieshStockExchange.Services.DataServices.Persistence.TransactionRow", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("BuyOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(20,10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SellOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransactionId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("SellerId");

                    b.HasIndex("StockId", "Currency", "Timestamp")
                        .HasDatabaseName("IX_Tx_Stock_Curr_Time");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("KieshStockExchange.Services.DataServices.Persistence.UserPreferencesRow", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DefaultCandleResolutionSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("ThemeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("KieshStockExchange.Services.DataServices.Persistence.UserRow", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("KieshStockExchange.Services.DataServices.Persistence.UserWatchlistEntryRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "StockId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserWatchlist_User_Stock");

                    b.ToTable("UserWatchlist", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
